// frontend_handson/student-portal-angular/src/app/course-card/course-card.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-course-card',
  standalone: true,
  templateUrl: './course-card.html',
  styleUrl: './course-card.css'
})
export class CourseCardComponent {

  @Input() name!: string;

  @Input() code!: string;

  @Input() credits!: number;

  @Input() grade!: string;

}

// frontend_handson/react_hands_on/student-portal-react/src/components/CourseCard.jsx
function CourseCard({
  id,
  name,
  code,
  credits,
  grade,
  onEnroll
}) {
  return (
    <div className="card">

      <h2>{name}</h2>

      <p>Course Code : {code}</p>

      <p>Credits : {credits}</p>

      <p>Grade : {grade}</p>

      <button onClick={() => onEnroll(id)}>
        Enroll
      </button>

    </div>
  );
}

export default CourseCard;
